datasource:
  driver: org.postgresql.Driver
  jdbcUrl: ${POSTGRES_URL}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}

spring:
  main:
    keep-alive: true
  application:
    name: dontcare
  datasource:
    driver-class-name: ${datasource.driver}
    username: ${datasource.username}
    url: ${datasource.jdbcUrl}
    password: ${datasource.password}

acn:
  outbox:
    scheduler:
      enabled: true


logging:
  level:
    root: INFO
    it.gov.acn: TRACE