global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'local'
    metrics_path: /actuator/prometheus
